myapp/urls.py
from django.urls import path
from myapp import views
app_name = 'myapp'
urlpatterns = [
 path(r'', views.index, name='index'),
 path(r'about', views.about, name='about'),
 path(r'<int:top_no>/', views.details),
 path(r'courses/<int:cour_id>/', views.coursedetail, name='coursedetail'),
 path(r'courses', views.courses, name='courses'),
 path(r'place_order', views.place_order, name='place_order'),
 path(r'login/', views.user_login, name='login'),
 path(r'logout/', views.user_logout, name='logout'),
 path(r'myaccount/', views.myaccount, name='myaccount'),
 path(r'register/', views.register, name='register'),
 path(r'myorders', views.myorders, name='myorders'),
 path(r'forgotPassword', views.forgotPassword, name = 'forgotPassword')
]

mywebappS222/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls'))
]

myapp/models.py
import decimal

from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
# Create your models here.

def validate_price(value):
    if value < 50 or value > 500:
        raise ValidationError(
            _('%(value)s is not in allowed range'),
            params={'value': value},
        )
class Topic(models.Model):
    name = models.CharField(name="name", max_length=200)
    category = models.CharField(name="category" , max_length=100, default="Development")

    def __str__(self):
        return f"Topic(name = {self.name}, category = {self.category})"

class Course(models.Model):
    topic = models.ForeignKey(Topic, related_name='courses', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[validate_price])
    for_everyone = models.BooleanField(default=True)
    description = models.TextField(max_length=300, null=True, blank=True)
    interested = models.PositiveIntegerField(default=0)
    stages = models.PositiveIntegerField(default=3)

    def discount(self):
        self.price = decimal.Decimal(0.90) * self.price

    def __str__(self):
        return f"Course (name= {self.name}, price = {self.price}, for_everyone = {self.for_everyone}" \
               f"description={self.description})"

class Student(models.Model):
    Image = models.ImageField(upload_to=None, height_field=None, width_field=None, blank = True, null = True)
    student_name = models.CharField(max_length=100)
    CITY_CHOICES = [('WS', 'Windsor'), ('CG', 'Calgery'), ('MR', 'Montreal'), ('VC', 'Vancouver')]
    school = models.CharField(max_length=50, null=True, blank=True)
    city = models.CharField(max_length=2, choices=CITY_CHOICES, default='WS')
    interested_in = models.ManyToManyField(Topic)

    class Meta:
        permissions = [
            ("canSeeMyAccount", "Can see the my account page"),
            {"canSeeMyOrders", "Can see the placed orders"}
        ]

    def __str__(self):
        return f"Student(name = {self.student_name}, city= {self.city}), school = {self.school}"

class Order(models.Model):
    course = models.ForeignKey(Course, related_name="courses", on_delete=models.CASCADE)
    Student = models.ForeignKey(Student, related_name="students", on_delete=models.CASCADE)
    levels = models.IntegerField(default=1)
    order_date = models.DateTimeField(default=timezone.now)
    ORDER_CHOICES = [('0', 'Cancelled'), ('1', 'Order Confirmed')]
    order_status = models.CharField(max_length=2, choices=ORDER_CHOICES, default='0')
    def __str__(self):
        return f"Order(levels = {self.levels}, order_date = {self.order_date}, order_status = {self.order_status})"

    def total_cost(self):
        sum = 0
        for course in self.course:
            sum += course.price
        return sum

myapp/forms.py
from django import forms
from myapp.models import Order

class InterestForm(forms.Form):
    CHOICES = [(1, 'YES'), (0, 'NO')]
    interested = forms.CharField(label='Interested', widget=forms.RadioSelect(choices=CHOICES))
    levels = forms.IntegerField(initial=1)
    comments = forms.CharField(
            widget=forms.Textarea(attrs={'cols': '30', 'rows':'15'}),
            label='Additional Comments', required=False)

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['Student', 'course', 'levels', 'order_date']
        widgets = {
            'Student': forms.RadioSelect,
            'order_date': forms.SelectDateWidget
        }

class RegisterForm(forms.Form):
    UserName = forms.CharField(label='UserName', widget=forms.TextInput(attrs={'class' :'form-control' }))
    Password = forms.CharField(label="Password", widget=forms.TextInput(attrs={'class' :'form-control' }))
    FirstName = forms.CharField(label="FirstName", widget=forms.TextInput(attrs={'class' :'form-control' }))
    LastName = forms.CharField(label="LastName", widget=forms.TextInput(attrs={'class' :'form-control' }))
    Email = forms.CharField(label="Email", widget=forms.TextInput(attrs={'class' :'form-control' }))
    CHOICES = [(1, 'YES'), (0, 'NO')]
    IsStudent = forms.CharField(label='Are you a Student?', widget=forms.RadioSelect(choices=CHOICES, attrs={'class':'custom-control-input'}), )

myapp/views.py
# Import necessary classes
# Import necessary classes
from curses.ascii import HT
from unicodedata import name
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail
from .forms import OrderForm,InterestForm, RegisterForm
from .models import Topic, Course, Student, Order
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from datetime import datetime
from django.contrib.auth.models import Group
from django.conf import settings 

def index(request):
    top_list = Topic.objects.all().order_by('id')[:10]
    if 'last_login' in request.session:
        recent_login = request.session['last_login']
    else:
        recent_login = "Your last login was more than one hour ago"
    # We are passing context variable {'top_list': top_list}
    return render(request, 'myapp/index.html', {'top_list': top_list, 'recent_login': recent_login})


def about(request):
    # We are NOT passing any context variable here.
    about_visits = request.COOKIES.get('about_visits', "1")
    about_visits = int(about_visits) + 1
    
    response = render(request,'myapp/about.html', {'about_visits': about_visits})  # django.http.HttpResponse
    response.set_cookie(key='about_visits', value=about_visits)
    return response

def details(request, top_no):
    get_object_or_404(Topic, pk=top_no)
    top_courses = Topic.objects.filter(id=top_no)
    # We are passing context variable here which is top_courses. All the topics which are stored in top_courses are passed to detail0.html
    context = {
        'top_courses': top_courses[0].name,
        'courses': Course.objects.filter(topic=top_no)
    }
    return render(request, 'myapp/detail.html', context=context)

def courses(request):
    courlist = Course.objects.all().order_by('id')
    return render(request, 'myapp/courses.html', {'courlist': courlist})

def place_order(request):
    msg = ''
    courlist = Course.objects.all()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if order.levels <= order.course.stages:
                order.save()
                if order.course.price > 150.00:
                    course = order.course
                    course.discount();
                    course.save()
                msg = 'Your course has been ordered successfully.'
            else:
                msg = 'You exceeded the number of levels for this course.'
            return render(request, 'myapp/order_response.html', {'msg': msg})
    else:
        form = OrderForm()
    return render(request, 'myapp/placeorder.html', {'form':form, 'msg':msg, 'courlist':courlist})

def coursedetail(request, cour_id):
    course = get_object_or_404(Course, pk=cour_id)
    if request.method == 'POST':
        form = InterestForm(request.POST)

        if form.is_valid() and form.cleaned_data['interested'] == '1':
                course.interested = course.interested + 1
                course.save()
                return redirect('/myapp')
    else:
        form = InterestForm()
    return render(request, 'myapp/coursedetail.html', {'form': form,'course': course})

def user_login(request):
    if request.method == 'POST':
        if request.session.test_cookie_worked():
            request.session.delete_test_cookie()
            print("Test cookie worked")
        else:
            print("Test cookie didn't work")
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                request.session['last_login'] = datetime.now().strftime("%H:%M:%S - %B %d, %Y")
                request.session.set_expiry(3600)
                #request.session.set_expiry(0)
                if request.GET.get('next') != None:
                    return redirect(request.GET.get('next'))
                else:
                    return HttpResponseRedirect(reverse('myapp:index'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        request.session.set_test_cookie()
        return render(request, 'myapp/login.html')


@login_required
def user_logout(request):
    #logout(request)
    request.session.flush()
    for key in list(request.session.keys()):
      del request.session[key]
    return HttpResponseRedirect(reverse(('myapp:index')))

@login_required(login_url='/myapp/login/')
def myaccount(request):
    user = None
    if request.user.has_perm("myapp.canSeeMyAccount"):
        user = request.user
        first_name = user.first_name
        last_name = user.last_name
        full_name = user.first_name+' '+user.last_name
        orders = Order.objects.filter(Student__student_name=full_name)
        topics = Student.objects.filter(student_name=full_name).values('interested_in__name')
        fname = request.user.first_name
        return render(request, 'myapp/my_account.html',
                      {"first_name": first_name, "last_name": last_name, "orders": orders, "topics": topics,
                       "fname": fname})
    else:
        return HttpResponse("You are not a registered student!")
    
def register(request):
    
    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid(): 
                username = form.cleaned_data['UserName']
                password = form.cleaned_data['Password']
                isStudent = form.cleaned_data['IsStudent']
                email = form.cleaned_data['Email']
                firstName = form.cleaned_data['FirstName']
                lastName = form.cleaned_data['LastName']
                user = User.objects.create_user(username, email, password)
                user.save()
                user.first_name = firstName
                user.last_name = lastName
                user.save()
                print(isStudent)
                if int(isStudent) == 1:
                    print(isStudent)
                    my_group = Group.objects.get(name='Student') 
                    my_group.user_set.add(user)
                    print(user.username)
                return redirect('/myapp/login')
    else:
        form = RegisterForm()
        return render(request, 'myapp/register.html', {'form' : form})

@login_required
def myorders(request):
    if request.user.has_perm("myapp.canSeeMyOrders"):
        studentName = request.user.get_full_name()
        orders = Order.objects.filter(Student__student_name=studentName)
        if(orders.count() > 0):
            return render(request, 'myapp/myorders.html', {'orders' : orders})
        else:
            return HttpResponse("You have not placed any orders!")
    else:
        return HttpResponse("You need to be a student to see orders")

def forgotPassword(request):
    if request.method == 'POST':
        email = request.POST.get('UserEmail')
        password = "new Password"
        user = User.objects.get(email = email)
        user.set_password(password)
        user.save()
        send_mail(
            subject="New Password", #subject
            message=password, #message
            from_email=settings.EMAIL_HOST_USER, #from
            recipient_list=[email], #to
        )
        return HttpResponse("We have emailed you a new password")
    else:
        return render(request, 'myapp/forgotPassword.html')

myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}
{% block title %}
    About
{% endblock %}
{% block body_block %}
    <p class="">This is an E-learning Website!Search our Topics to find all available Courses.</p>
    <br>
    <h3>Number of visits: {{ about_visits }}</h3>
{% endblock %}

myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
    <style>
        body{
            background-color: aqua;
        }
    </style>
</head>
<body>
    <p>This is an E-learning Website!Search our Topics to find all available Courses.</p>
{#    Hardcode URL#}
{#    <p><a href="/myapp">Main Page</a></p>#}

{#    URL namespacing#}
    <p><a href="{% url 'myapp:index' %}">Main Page</a></p>
</body>
</html>

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/bootstrap.css' %}"/>
    <title>E-Learning WebApp - {% block title %}Welcome!{% endblock %}</title>
 </head>
 <body>
     <div>
         {% if user.is_authenticated %}
                <span><a style="float:right; text-decoration: none ; " class="btn btn-error" href="{% url 'myapp:logout' %}">Logout</a>
            </span>
         {% else %}
         <span class="navbar">
            <span class="btn btn-success m-2"><a style="float:right; text-decoration: none; color:white; " href="{% url 'myapp:login' %}">Login</a>
            </span>
            <span class="btn btn-success m-2"><a style="float:right; text-decoration: none; color:white; " href="{% url 'myapp:register' %}">Register</a>
            </span>
        </span>
         {% endif %}
        <br/>
        <div class="p-2 m-4">
            <h1>{% block myhdg %}Hello {{ user }} {% endblock %}
        </div>
         </h1>

         {% block body_block %}*** {% endblock %}
     </div>
     <hr>
       <div class="pt-5 mt-5  ">
        <ul class="list-group-flush">
            <li class="list-group-item list-group-item-success"><a style="text-decoration:none" href="{% url 'myapp:about' %}">Find out about our ELearning site</a></li>
            <li class="list-group-item list-group-item-success"><a style="text-decoration:none"  href = "{% url 'myapp:index' %}">Click here to
           return to main page</a></li>
            <li class="list-group-item list-group-item-success"><a style="text-decoration:none"  href = "{% url 'myapp:courses' %}">List of all courses</a></li>
        </ul>
    </div>
 </body>
</html>

myapp/templates/myapp/coursedetail.html
{% extends 'myapp/base.html' %}
{% block title %}
    Place Order
{% endblock %}
{% block body_block %}

    {{ course.name }}
        <br/>
    {{ course.interested }}
    <br/>
    {{ course.price }}
    <br/>
    {%  if not course.for_everyone %}
        Course is not available for all
    {% endif %}
    <form action="{% url 'myapp:coursedetail' course.id %}" method="POST">
       {% csrf_token %}
       {{ form }}
       <input type="submit" value="Submit" />
   </form>
{% endblock %}

myapp/templates/myapp/courses.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    {% for course in courlist %}
    <a href = "{% url 'myapp:coursedetail' course.id %}">{{ course.name }}</a>
        <br/>
    {% endfor %}
    <li><a href = "{% url 'myapp:place_order' %}">Place Order</a></li>
{% endblock %}

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% block title %}
    Details
{% endblock %}
{% block body_block %}
<ul class="list-group p-3">
    <h2 class="bg-light">{{  top_courses }}</h2>
    <hr/>
    {% for course in courses %}
        <li class="list-group-item list-group-item-primary p-2 ">    Course Name: {{ course.name }} </li>
    {% endfor %}
</ul>
{% endblock %}

myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
</head>
<body>

    {% for course in top_courses %}
        <p> {{ course.topic.id }} :  {{ course.topic }}  :  Course Name: {{ course.name }} </p>
    {% endfor %}
    <p><a href="{% url 'myapp:index' %}">Main Page</a></p>
</body>
</html>

myapp/templates/myapp/forgotPassword.html
{% extends 'myapp/base.html' %}
{% block title %}
    Details
{% endblock %}
{% block body_block %}
     <div class="card m-5 p-3">
        <form method="post" class="form p-3">
            {% csrf_token%}
            <div class="form-group p-3">
                <label class="form-label">Enter Email</label>
            <input type="text" class="form-control" name="UserEmail"></input>
            </div>
            <div class=" form-group p-3">
                <input type="submit" value="Send Password" class="btn btn-primary">
            </div>
         </form>
     </div>
{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    {% if user.is_authenticated %}
        <div class="card p-3 m-3 bg-warning">
            <h3>Recent Login: {{recent_login}}</h3>
        </div>
    
    {% endif %}

    {% if top_list %}
    <div class="m-3 p-3">
        <h2 >List of Topics</h2>
    <ol class="list-group">
    {% for top in top_list %}
        <li class="list-group-item" > <a style="text-decoration:none" href= "{{top.id}}" > {{top.name}} </a> </li>
    {% endfor %}
    </ol>
    {% else %}
    <strong>There are no available topics!</strong>
    </div>
    {% endif %}
{% endblock %}

myapp/templates/myapp/my_account.html
{% extends 'myapp/base.html' %}
{% block title %}
    My Account
{% endblock %}
{% block body_block %}
    <h2> Full Name : {{ first_name }} {{ last_name }}</h2>
    {% if orders %}
        <h3>Orders</h3>
        <ul>
            {% for order in orders %}
                <li>{{ order.course }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <h2>You don't have any orders</h2>
    {% endif %}
    {% if topics %}
        <h3>Interested In</h3>
        <ul>
            {% for topic in topics %}
                <li>{{ topic.interested_in__name }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <h2>You don't have any Interests</h2>
    {% endif %}

    <br/>
{% endblock %}

myapp/templates/myapp/myorders.html
{% extends 'myapp/base.html' %}
{% block title %}
    Details
{% endblock %}
{% block body_block %}
    <h3>YourOrders</h3>
    {% for order in orders %}
        <p><label>CourseName:</label>{{order.course.name}}</p>
        <p><label>Order Status:</label>{{order.order_status}}</p>
    {% endfor %}
{% endblock %}

myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    {{ msg }}
{% endblock %}

myapp/templates/myapp/placeorder.html
{% extends 'myapp/base.html' %}
{% block title %}
    Place Order
{% endblock %}
{% block body_block %}
    {% for course in courlist %}
    {{ course }}
        <br/>
    {% endfor %}

   <form action="" method="post">
       {% csrf_token %}
       {{ form }}
       <input type="submit" value="Submit" />
   </form>


{% endblock %}

myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}
{% block title %}
    Place Order
{% endblock %}
{% block body_block %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-9 m-auto">
            <div class="card p-5 m-3">
                <div class="card-title"> Register Form</div>
                <form action="" method="post" class="form">
                    {% csrf_token %}
                    {{ form }}
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary" value="Register" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}